### ISSUE TITLE
Problem to install application

### ISSUE THREAD

**Issue by ewerton-silva00** [adamcooke/staytus#276]
Hi, folks.

I'm with a problem to install the application. When i execute the command bellow get a error:

Command: `bundle exec rake staytus:build`

Error Message:

`
rake aborted!
TypeError: no implicit conversion of Fixnum into String
/opt/app/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config.rb:12:in `[]='
/opt/app/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config.rb:12:in `block in load'
/opt/app/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config.rb:11:in `each'
/opt/app/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config.rb:11:in `load'
/opt/app/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config/railtie.rb:7:in `block (2 levels) in <class:Railtie>'
/opt/app/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config/railtie.rb:4:in `each'
/opt/app/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config/railtie.rb:4:in `block in <class:Railtie>'
/opt/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
/opt/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
/opt/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
/opt/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/opt/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:49:in `each'
/opt/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/opt/app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.6/lib/rails/application.rb:91:in `inherited'
/opt/app/config/application.rb:10:in `<module:Staytus>'
/opt/app/config/application.rb:9:in `<top (required)>'
/opt/app/Rakefile:4:in `require'
/opt/app/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
`

Can you help me?

**Comment by ewerton-silva00** [comment]
Problem resolved.

https://github.com/adamcooke/staytus/issues/222
