### ISSUE TITLE
Email issues

### ISSUE THREAD

**Issue by veronicap1** [adamcooke/staytus#45]
Hi,
I'm a newbie and have issues to get email working. I've configured the server (Amazon linux) to send email and it works fine from the CLI but I don't get the email to work from the application. If I try to subscribe I get the following error message in production.log:

ArgumentError (SMTP-AUTH requested but missing secret phrase):
  lib/staytus/email.rb:38:in `deliver'
  app/models/subscriber.rb:41:in `send_verification_email'
  app/controllers/pages_controller.rb:58:in `subscribe_by_email'
  app/controllers/application_controller.rb:15:in `set_time_zone'

I've googled but I can't find anything that solves my problem. Any suggestion on what I am missing?
BR
Veronica

**Comment by veronicap1** [comment]
Solved, changed sendmail to postfix and now it works
